### ISSUE TITLE
<PRUEBA> Validación por detalle de entidad

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/MiembrosCNAD#10]
### Para acceder:

Adjunto ruta de publicación del sistema mencionado en el asunto del correo: 

http://10.15.0.40/Rno_Cnad/

Solamente deberá permitir postular los siguientes tipos de entidad:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/c889a119-1802-4d7e-ae27-ebb9fd9f1d3c)

Datos de prueba de casos exitosos:

NOTA: estos podrán postular de manera rápida eso quiere decir que no se necesita ingresar el siguiente rut.

Id_detalle_entidad= 7

Rut: 65031772
Nombre: FEDERACION DEPORTIVA NACIONAL AJEDREZ FEDERADO DE CHILE
Folio: 1304148

Rut: 65062876
Nombre: FEDERACION DEPORTIVA NACIONAL DE TIRO AL BLANCO
Folio: 701437

👎 1302044 => Este no debería poder postular:

**Comment by felipedonoso** [comment]
@danteghirardelli, favor de continuar con esta tarea, por favor

**Comment by danteghirardelli** [comment]
### Seguir con las Pruebas de Postulación Arbitraje:
![image](https://user-images.githubusercontent.com/21196249/51839653-93dcf800-22e8-11e9-97b4-bca9898f9764.png)
![image](https://user-images.githubusercontent.com/21196249/51839700-b66f1100-22e8-11e9-8bf7-949ca1d575e5.png)
![image](https://user-images.githubusercontent.com/21196249/51839758-e1596500-22e8-11e9-981d-100c594c5510.png)
![image](https://user-images.githubusercontent.com/21196249/51839833-2382a680-22e9-11e9-871d-555f2325efc7.png)
![image](https://user-images.githubusercontent.com/21196249/51839895-4f9e2780-22e9-11e9-9626-a3a64c19b5ee.png)
![image](https://user-images.githubusercontent.com/21196249/51839959-79574e80-22e9-11e9-89a3-b6249b8d805c.png)
![image](https://user-images.githubusercontent.com/21196249/51839975-85dba700-22e9-11e9-9775-db03ed02e367.png)
![image](https://user-images.githubusercontent.com/21196249/51839991-925fff80-22e9-11e9-8786-adb78f4f3a29.png)
Postulación Ingresada con Éxito.

**Comment by danteghirardelli** [comment]
### Nueva Postulación:
![image](https://user-images.githubusercontent.com/21196249/51840359-9ccec900-22ea-11e9-8936-77de05042fd3.png)
![image](https://user-images.githubusercontent.com/21196249/51840396-c12aa580-22ea-11e9-8f82-f20b5c2f4f38.png)
![image](https://user-images.githubusercontent.com/21196249/51840487-fdf69c80-22ea-11e9-8ee7-4a80d8be584c.png)
![image](https://user-images.githubusercontent.com/21196249/51840545-1bc40180-22eb-11e9-8ead-aaa6ce2975d5.png)
![image](https://user-images.githubusercontent.com/21196249/51840583-35654900-22eb-11e9-8cdd-58913bd1c779.png)
![image](https://user-images.githubusercontent.com/21196249/51840609-431ace80-22eb-11e9-9fec-f4f4f71f762e.png)
![image](https://user-images.githubusercontent.com/21196249/51840633-52018100-22eb-11e9-82cb-ab96e500d986.png)
Postulación Ingresada con éxito.
@felipedonoso @cristsaavedra

**Comment by danteghirardelli** [comment]
### Continuar con las Postulaciones:
![image](https://user-images.githubusercontent.com/21196249/51840839-ee2b8800-22eb-11e9-950d-d12e2879071a.png)
![image](https://user-images.githubusercontent.com/21196249/51840888-0d2a1a00-22ec-11e9-914f-5434edf38379.png)
![image](https://user-images.githubusercontent.com/21196249/51840991-4cf10180-22ec-11e9-8d6a-e95cad032876.png)
![image](https://user-images.githubusercontent.com/21196249/51841052-7316a180-22ec-11e9-9f16-40704653a7be.png)
![image](https://user-images.githubusercontent.com/21196249/51841066-7ca00980-22ec-11e9-8b03-75a10adb6e6f.png)
![image](https://user-images.githubusercontent.com/21196249/51841086-8d507f80-22ec-11e9-8823-37d62638d023.png)
Postulación Ingresada con Éxito.
@felipedonoso @cristsaavedra 

### Conclusión:
El Sistema cumple satisfactoriamente con la Postulación.
