### ISSUE TITLE
<PRUEBA> Caso exitoso id_detalle_entidad = 7

### ISSUE THREAD

**Issue by felipedonoso** [InstitutoNacionalDeDeportes/MiembrosCNAD#3]
**Adjunto ruta de publicación del sistema mencionado en el asunto del correo:** 

http://10.15.0.40/Rno_Cnad/

Cuando te pida el segundo folio deberás ingresar cualquiera de estos 02:

Folio: **1304148**
Folio: **701437**

**Comment by felipedonoso** [comment]
Solamente deberá permitir postular los siguientes tipos de entidad:

![image.png](https://images.zenhubusercontent.com/5a6086fc4b5806bc2bc33dfe/c889a119-1802-4d7e-ae27-ebb9fd9f1d3c)

**Datos de prueba de casos exitosos:**

**NOTA**: estos podrán postular de manera rápida eso quiere decir que no se necesita ingresar el siguiente rut.

### Id_detalle_entidad= 7

**Rut**: 65031772
Nombre: FEDERACION DEPORTIVA NACIONAL AJEDREZ FEDERADO DE CHILE
Folio: 1304148

**Rut**: 65062876
Nombre: FEDERACION DEPORTIVA NACIONAL DE TIRO AL BLANCO
Folio: 701437

**Comment by felipedonoso** [comment]
@danteghirardelli estimado, al ingresar el rut de la persona, luego ingresar el número de folio indicado anteriormente debería poder permitir postular de manera rápida.

Eso quiere decir que solo adjuntas los documentos y listos.

Saludos!

**Comment by danteghirardelli** [comment]
http://10.15.0.40/Rno_Cnad/

Segunda Prueba para Folio 701437
![image](https://user-images.githubusercontent.com/21196249/51746926-9cce8f00-2086-11e9-9f91-7604c21c9aa4.png)
![image](https://user-images.githubusercontent.com/21196249/51746994-dd2e0d00-2086-11e9-80bd-28058e2c9031.png)
![image](https://user-images.githubusercontent.com/21196249/51747045-0189e980-2087-11e9-94be-a797322a06db.png)
![image](https://user-images.githubusercontent.com/21196249/51747091-3007c480-2087-11e9-97a8-3bf7d7369a67.png)
![image](https://user-images.githubusercontent.com/21196249/51747133-5a598200-2087-11e9-96d9-a12c50008d43.png)
![image](https://user-images.githubusercontent.com/21196249/51747155-6a716180-2087-11e9-8503-2901f47b561a.png)
![image](https://user-images.githubusercontent.com/21196249/51747181-75c48d00-2087-11e9-882d-3608c06dd232.png)

Mail correcto
![image](https://user-images.githubusercontent.com/21196249/51747245-a60c2b80-2087-11e9-9caf-1b98f816bf83.png)
![image](https://user-images.githubusercontent.com/21196249/51747265-b7edce80-2087-11e9-8ed3-475383f612eb.png)

Conclusión:
La Postulación resultó exitosa para Rut 15348624
Folio: 701437

@felipedonoso @cristsaavedra 

Gracias por las mejoras Cristian.
